# Python Basics

## List, Set, Dist, Tuple

## Day 1  --  7th Jan

In [1]:
# List -> []
# Dict -> {}
# Tuple -> ()


In [2]:
#Problem:- From 100 random numbers find the list of only odd(not prime) and prime numbers

In [3]:
import random

In [4]:


random_numbers = []
odd_not_prime = []
prime = []
even = []



In [5]:
for i in range(0,100):
    random_numbers.append(random.randint(200, 400))



In [6]:
def is_prime_number(x):
    if x >= 2:
        for y in range(2,x):
            if ( x % y  == 0):
                return False
    else:
        return False
    
    return True
        
    

In [7]:
is_prime_number(19)

True

In [8]:
# build the prime and odd_not_prime list and keep even to assert we are on track and not leaving any number behind
for i in random_numbers:
    if (i % 2 != 0):
        if (is_prime_number(i)):
            prime.append(i)
        else:
            odd_not_prime.append(i)
    else:
        even.append(i)
    

In [9]:
len(prime)

21

In [10]:
len(odd_not_prime)

32

In [11]:
len(even)

47

In [12]:
len(prime) + len(odd_not_prime) + len(even)

100

In [13]:
# now build up the dict as the above 

In [14]:

random_numbers_for_dict = []
odd_prime_dict = {'prime' : [], 'odd_not_prime' : [], 'even' : []}


In [15]:
for i in range(0,100):
    random_numbers_for_dict.append(random.randint(200, 400))



In [16]:
# build the prime and odd_not_prime Hash Map, or Dict
# and keep even to assert we are on track and not leaving any number behind
for i in random_numbers_for_dict:
    if (i % 2 != 0):
        if (is_prime_number(i)):
            odd_prime_dict['prime'].append(i)
        else:
            odd_prime_dict['odd_not_prime'].append(i)
    else:
        odd_prime_dict['even'].append(i)

In [17]:
len( odd_prime_dict['prime'])

13

In [18]:
len(odd_prime_dict['odd_not_prime'])

30

In [19]:
len(odd_prime_dict['even'])

57

In [20]:
len( odd_prime_dict['prime']) + len(odd_prime_dict['odd_not_prime']) + len(odd_prime_dict['even'])

100

## ------------------ Day 2 ------8th Jan ----------------

In [1]:
import numpy as np

In [7]:
l1 = [2,4,5,6]
l2 = [6,8,10,12]

l1_1 = [[2,4,5,6]]
l2_2 = [[6,8,10,12]]

In [3]:
l1_array = np.array(l1)

In [4]:
l1_array


array([2, 4, 5, 6])

In [12]:
# Note this is somewhat absurd since this is the tensor?, which takes the number of channels first in account
l1_array.shape

(4,)

In [8]:
l1_1_array = np.array(l1_1)

In [9]:
l1_1_array

array([[2, 4, 5, 6]])

In [10]:
l1_1_array.shape

(1, 4)

In [13]:
l3_3_array = np.concatenate([l1_1, l2_2])

In [14]:
l3_3_array

array([[ 2,  4,  5,  6],
       [ 6,  8, 10, 12]])

In [16]:
l3_array = np.concatenate([l1, l2])

In [17]:
l3_array

array([ 2,  4,  5,  6,  6,  8, 10, 12])

In [18]:
np.max(l3_3_array, axis=0)

array([ 6,  8, 10, 12])

In [19]:
np.max(l3_3_array, axis=1)

array([ 6, 12])

In [20]:
np.max(l3_3_array, axis=0).shape

(4,)

In [21]:
np.max(l3_3_array, axis=1).shape

(2,)

In [22]:
np.argmax(l3_3_array, axis=0)

array([1, 1, 1, 1])

In [23]:
np.argmax(l3_3_array, axis=1)

array([3, 3])

In [25]:
np.sum(l3_3_array, axis =0)

array([ 8, 12, 15, 18])

In [26]:
np.sum(l3_3_array, axis =1)

array([17, 36])

In [ ]:
#Classes & Objects