In [38]:
import pandas as pd

In [39]:
data = pd.read_csv("./data/mushrooms.csv")

In [40]:
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [41]:
data['class'].unique()

array(['p', 'e'], dtype=object)

In [42]:
import numpy as np

In [43]:
row_indices = np.arange(0,len(data))

In [44]:
row_indices

array([   0,    1,    2, ..., 8121, 8122, 8123])

In [45]:
np.random.shuffle(row_indices)

In [46]:
row_indices

array([5356,  719, 8041, ..., 1212, 6272, 3482])

In [47]:
data = data.iloc[row_indices,0:2]

In [48]:
data

class cap-shape
5356     p         f
719      e         s
8041     p         k
6505     p         f
588      e         s
...    ...       ...
5536     e         f
627      e         s
1212     e         f
6272     p         x
3482     e         f

[8124 rows x 2 columns]

In [49]:
training_data = data.iloc[0:int(0.75*len(data))]

In [50]:
training_data

class cap-shape
5356     p         f
719      e         s
8041     p         k
6505     p         f
588      e         s
...    ...       ...
6968     p         f
1082     e         b
87       e         x
6226     p         f
4057     p         x

[6093 rows x 2 columns]

In [51]:
remaining_data = data.iloc[int(0.75*len(data)):]

In [52]:
remaining_data

class cap-shape
132      e         f
1019     e         x
5930     e         x
7782     e         b
5837     p         x
...    ...       ...
5536     e         f
627      e         s
1212     e         f
6272     p         x
3482     e         f

[2031 rows x 2 columns]

In [53]:
cross_validation = remaining_data.iloc[0:int(0.33*len(remaining_data))]

In [54]:
cross_validation

class cap-shape
132      e         f
1019     e         x
5930     e         x
7782     e         b
5837     p         x
...    ...       ...
3103     p         f
1506     p         f
7738     p         k
6487     p         f
7132     p         k

[670 rows x 2 columns]

In [55]:
testing_data = remaining_data.iloc[int(0.33*len(remaining_data)):]

In [56]:
testing_data

class cap-shape
6155     p         k
1358     e         f
7278     e         b
4737     p         f
6439     p         x
...    ...       ...
5536     e         f
627      e         s
1212     e         f
6272     p         x
3482     e         f

[1361 rows x 2 columns]

In [57]:
p_cap = training_data['class'].value_counts()

In [58]:
p_cap

e    3151
p    2942
Name: class, dtype: int64

In [59]:
p_cap = np.array(p_cap)

In [60]:
p_cap = p_cap/training_data.shape[0]

In [61]:
p_cap

array([0.51715083, 0.48284917])

In [62]:
unique_cap_shape_values = data['cap-shape'].unique()

In [63]:
unique_cap_shape_values

array(['f', 's', 'k', 'x', 'b', 'c'], dtype=object)

In [64]:
e_training_data = training_data[training_data['class'] == 'e']

In [65]:
p_training_data = training_data[training_data['class'] == 'p']

In [66]:
e_cap_shape_unique_values = e_training_data['cap-shape'].unique()

In [67]:
e_cap_shape_unique_values

array(['s', 'f', 'x', 'k', 'b'], dtype=object)

In [68]:
p_cap_shape_unique_values = p_training_data['cap-shape'].unique()

In [69]:
p_cap_shape_unique_values

array(['f', 'k', 'x', 'b', 'c'], dtype=object)

In [70]:
def calculate_p_cap_shape (dataframe):
    
    p_cap_shape_on = dict(dataframe['cap-shape'].value_counts())
    
    print(p_cap_shape_on)

    value_counts = np.array(list(p_cap_shape_on.values()))
    
    print(value_counts)

    rf = value_counts/dataframe.shape[0]
    
    print(rf)

    p_cap_shape_on = dict(zip(p_cap_shape_on.keys(),rf))
    
    return p_cap_shape_on

In [71]:
e_training_data.shape

(3151, 2)

In [72]:
p_cap_shape_on_e = calculate_p_cap_shape(e_training_data)

{'x': 1482, 'f': 1188, 'b': 291, 'k': 166, 's': 24}
[1482 1188  291  166   24]
[0.47032688 0.37702317 0.09235163 0.05268169 0.00761663]


In [73]:
p_cap_shape_on_e

{'x': 0.47032688035544273,
 'f': 0.37702316724849255,
 'b': 0.09235163440177721,
 'k': 0.05268168835290384,
 's': 0.007616629641383688}

In [74]:
p_cap_shape_on_p = calculate_p_cap_shape(p_training_data)

{'x': 1291, 'f': 1159, 'k': 454, 'b': 34, 'c': 4}
[1291 1159  454   34    4]
[0.43881713 0.39394969 0.15431679 0.01155676 0.00135962]


In [75]:
p_cap_shape_on_p

{'x': 0.4388171312032631,
 'f': 0.393949694085656,
 'k': 0.15431679129843645,
 'b': 0.011556764106050306,
 'c': 0.0013596193065941536}

In [76]:
p_cap_shape_on_e['c'] = 1/(e_training_data.shape[0] + training_data['cap-shape'].unique().shape[0])

In [77]:
p_cap_shape_on_p['s'] = 1/(p_training_data.shape[0] + training_data['cap-shape'].unique().shape[0])

In [78]:
p_cap_shape_on_e

{'x': 0.47032688035544273,
 'f': 0.37702316724849255,
 'b': 0.09235163440177721,
 'k': 0.05268168835290384,
 's': 0.007616629641383688,
 'c': 0.0003167564143173899}

In [79]:
p_cap_shape_on_p

{'x': 0.4388171312032631,
 'f': 0.393949694085656,
 'k': 0.15431679129843645,
 'b': 0.011556764106050306,
 'c': 0.0013596193065941536,
 's': 0.00033921302578018993}

In [80]:
def predicted_category(x):
    
    likelihood_e = p_cap_shape_on_e[x]
    
    likelihood_p = p_cap_shape_on_p[x]
    
    numerator = likelihood_p * p_cap[1]
    
    denominator = numerator + (likelihood_e * p_cap[0])
    
    posterior_p = numerator/denominator
    
    return int(posterior_p > 0.5)

In [81]:
predicted_answers = []

for cap_shape in cross_validation['cap-shape']:
    
    predicted_answers.append(predicted_category(cap_shape))

In [82]:
predicted_answers = np.array(predicted_answers)

In [83]:
predicted_answers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [84]:
cross_validation['class'].replace(to_replace=['e','p'],value=[0,1],inplace=True)

/usr/local/lib/python3.7/site-packages/pandas/core/generic.py:6788: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [85]:
actual_answers = np.array(cross_validation['class'])

In [86]:
actual_answers

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,

In [87]:
correct_count = np.count_nonzero(predicted_answers == actual_answers)

In [88]:
correct_count

375

In [89]:
percent_accuracy = (correct_count/cross_validation.shape[0])*100

In [90]:
percent_accuracy

55.970149253731336